### ISSUE TITLE
Video size not changing

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/oblique#111]
Issue: When we place YouTube or Vimeo video using iFrame, it does not reflect the height and width parameter. Instead, it shows the videos in full width only. http://prntscr.com/iupsde, http://prntscr.com/iupsms

I tried checking with Video type post. It was same there too.

Ticket: https://secure.helpscout.net/conversation/545674400/157612?folderId=212385

@rodica-andronache

**Comment by cosmin-serbanescu** [comment]
It was a problem with fitvids.js - the thing that makes videos responsive. I've added a checkbox in Customizer -> General  called 'Disable FitVids?' that enables/disables that js

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu what I would suggest here ( and in Oblique pro ) is to try:
- use wp_localize_script instead of using js in php like you did. With wp_localize_script you can send a parameter ( the value of your theme_mod for ex ) and use it in the js file where fitvid is, to know if you need it or not.
for ex: https://github.com/Codeinwp/zerif-pro/blob/f3a598fc38a9c9c143ca980fe59ce5d7b4d52489/functions.php#L598
https://github.com/Codeinwp/zerif-pro/blob/production/js/jquery.knob.min.js#L39

- Have a more user-friendly title instead of Disable FitVids, as a user would not understand what that it

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu I tried adding a video with width 10px. This is how it looks in customizer https://prnt.sc/izm8nq and this is how it looks on the site https://prnt.sc/izm8rb by **default**.
This is happening because when you defined the disable_fitvids control, you added a default value of 0, but when you used it with get_theme_mod in functions.php, you didn't add that default value, like this:
wp_localize_script( 'oblique-scripts', 'oblique_disable_fitvids_var', array( 'oblique_disable_fitvids' => get_theme_mod( 'disable_fitvids',0 ) ) );

The idea here is that always when defining a control in customizer with a default value, you need to add that exact default value wherever you use get_theme_mod 👍 

Please change this in oblique pro, if it's the same :)

**Comment by rodica-andronache** [comment]
another thing here :) From what I tested, something is not working ok at a first install. https://prnt.sc/iznuku By default, the option is not checked, but the videos act as if that would be checked. Can you check too? It's just in the default case ( you can clear the theme mod options in the database to test )

**Comment by cosmin-serbanescu** [comment]
it was a matter of defaults '0' vs 0 apparently

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu for me it's still not working ok 🗡 https://prnt.sc/j07jx9 by default, the checkbox is checked and it shouldn't.
I think the solution is to use `false` as default value and have this check in scripts.js:
`if ( ! oblique_disable_fitvids_var.oblique_disable_fitvids )`

Could you please check? 💃

**Comment by cosmin-serbanescu** [comment]
thanks @rodica-andronache , it did the trick!
