### ISSUE TITLE
Line appearing on site

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/oblique#88]
Line appears on site. HS thread: https://secure.helpscout.net/conversation/369252234/133805/
cc @rodica-andronache

**Comment by rodica-andronache** [comment]
@suyogyashukla I know what this issue is about because we talked about it before, but it would be better to include more details for each issue created :) The helpscout ticket should be just a reference. The github issue should contain all details the developer needs to investigate/fix it without reading the whole HS ticket. This is also helping because the issue can be assigned to someone in a couple of weeks maybe, and nobody we'll remember what it was about than, maybe neither you :)

**Comment by suyogyashukla** [comment]
@rodica-andronache Okay cool. I didn't include because we talked about it already but I get your point. Will include all the details from now :)
